package GUI;

import Controller.ConfiguracaoMaster;
import Controller.FuncionarioController;
import Utilitarios.CurrencyFormater;
import java.util.ArrayList;
import java.util.Currency;
import java.util.List;
import javax.swing.JOptionPane;


/**
 * The type Funcionarios form.
 *
 * @author Java
 */
public class FuncionarioForm extends CreditoForm {

    /**
     * The Currency formater.
     */
    CurrencyFormater currencyFormater = new CurrencyFormater();
    /**
     * The Funcionario c.
     */
    FuncionarioController FuncionarioC = new FuncionarioController();

    /**
     * The Cargo.
     */
    List<String> Cargo;
    /**
     * The Cidades.
     */
    List<String> Cidades;
    /**
     * The Id cidade.
     */
    List<Integer> IdCidade;

    /**
     * The Bairros.
     */
    List<String> Bairros;
    /**
     * The Id bairro.
     */
    List<Integer> IdBairro;

    /**
     * The Ordem.
     */
    List<Integer> Ordem;

    /**
     * Instantiates a new Funcionarios form.
     */
    public FuncionarioForm() {
        initComponents();
        
        Cargo = new ArrayList<>();
        Cidades = new ArrayList<>();
        IdCidade = new ArrayList<>();
        Bairros = new ArrayList<>();
        IdBairro = new ArrayList<>();
        Ordem = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtSobrenome = new javax.swing.JTextField();
        cbbCargo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtDataAdm = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        edtDataDem = new com.toedter.calendar.JDateChooser();
        edtCarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtSalario = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbCidade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbbBairro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edtCep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        edtRg = new javax.swing.JTextField();
        chbFun = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        chbUsr = new javax.swing.JCheckBox();
        lblLogin = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblPermissao = new javax.swing.JLabel();
        cbbPermissao = new javax.swing.JComboBox<>();
        edtSenha = new javax.swing.JPasswordField();
        chbAtivo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnBusscar = new javax.swing.JButton();
        btnRemoverFiltro = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        setTitle(bundle.getString("FuncionarioForm.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cargo", "Salário", "Usuário", "Usuário Ativo", "Funcionário Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblFuncionario.setName("tblFuncionario"); // NOI18N
        jScrollPane1.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title0_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title1_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title2_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title3_2")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title4_1")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title5_1")); // NOI18N
            tblFuncionario.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("FuncionarioForm.tblFuncionario.columnModel.title6")); // NOI18N
        }

        jLabel1.setText(bundle.getString("FuncionarioForm.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        edtNome.setText(bundle.getString("FuncionarioForm.edtNome.text")); // NOI18N
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setEnabled(false);
        edtNome.setName("edtNome"); // NOI18N

        jLabel11.setText(bundle.getString("FuncionarioForm.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        edtSobrenome.setText(bundle.getString("FuncionarioForm.edtSobrenome.text")); // NOI18N
        edtSobrenome.setEnabled(false);
        edtSobrenome.setName("edtSobrenome"); // NOI18N

        cbbCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbCargo.setEnabled(false);
        cbbCargo.setName("cbbCargo"); // NOI18N

        jLabel2.setText(bundle.getString("FuncionarioForm.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("FuncionarioForm.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        edtDataAdm.setEnabled(false);
        edtDataAdm.setName("edtDataAdm"); // NOI18N

        jLabel4.setText(bundle.getString("FuncionarioForm.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        edtDataDem.setEnabled(false);
        edtDataDem.setName("edtDataDem"); // NOI18N

        edtCarga.setText(bundle.getString("FuncionarioForm.edtCarga.text")); // NOI18N
        edtCarga.setEnabled(false);
        edtCarga.setName("edtCarga"); // NOI18N

        jLabel6.setText(bundle.getString("FuncionarioForm.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        currencyFormater.CurrencyFormater(edtSalario);
        edtSalario.setText(bundle.getString("FuncionarioForm.edtSalario.text")); // NOI18N
        edtSalario.setEnabled(false);
        edtSalario.setName("edtSalario"); // NOI18N
        edtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSalarioActionPerformed(evt);
            }
        });

        jLabel5.setText(bundle.getString("FuncionarioForm.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setText(bundle.getString("FuncionarioForm.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        cbbCidade.setEnabled(false);
        cbbCidade.setName("cbbCidade"); // NOI18N
        cbbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCidadeItemStateChanged(evt);
            }
        });
        cbbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCidadeActionPerformed(evt);
            }
        });

        jLabel8.setText(bundle.getString("FuncionarioForm.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        cbbBairro.setEnabled(false);
        cbbBairro.setName("cbbBairro"); // NOI18N

        jLabel10.setText(bundle.getString("FuncionarioForm.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        edtEndereco.setText(bundle.getString("FuncionarioForm.edtEndereco.text")); // NOI18N
        edtEndereco.setEnabled(false);
        edtEndereco.setName("edtEndereco"); // NOI18N

        jLabel9.setText(bundle.getString("FuncionarioForm.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        edtCep.setText(bundle.getString("FuncionarioForm.edtCep.text")); // NOI18N
        edtCep.setEnabled(false);
        edtCep.setName("edtCep"); // NOI18N

        jLabel14.setText(bundle.getString("FuncionarioForm.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        edtCpf.setText(bundle.getString("FuncionarioForm.edtCpf.text")); // NOI18N
        edtCpf.setEnabled(false);
        edtCpf.setName("edtCpf"); // NOI18N

        jLabel15.setText(bundle.getString("FuncionarioForm.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        edtRg.setText(bundle.getString("FuncionarioForm.edtRg.text")); // NOI18N
        edtRg.setEnabled(false);
        edtRg.setName("edtRg"); // NOI18N

        chbFun.setSelected(true);
        chbFun.setText(bundle.getString("FuncionarioForm.chbFun.text")); // NOI18N
        chbFun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbFun.setEnabled(false);
        chbFun.setName("chbFun"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair-1.png"))); // NOI18N
        btnSair.setToolTipText(bundle.getString("FuncionarioForm.btnSair.toolTipText")); // NOI18N
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setDisabledIcon(null);
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cancel-1.png"))); // NOI18N
        btnCancelar.setToolTipText(bundle.getString("FuncionarioForm.btnCancelar.toolTipText")); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setDisabledIcon(null);
        btnCancelar.setEnabled(false);
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText(bundle.getString("FuncionarioForm.btnSalvar.toolTipText")); // NOI18N
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setDisabledIcon(null);
        btnSalvar.setEnabled(false);
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir2.png"))); // NOI18N
        btnNovo.setToolTipText(bundle.getString("FuncionarioForm.btnNovo.toolTipText")); // NOI18N
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        chbUsr.setText(bundle.getString("FuncionarioForm.chbUsr.text")); // NOI18N
        chbUsr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbUsr.setEnabled(false);
        chbUsr.setName("chbUsr"); // NOI18N
        chbUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbUsrActionPerformed(evt);
            }
        });

        lblLogin.setText(bundle.getString("FuncionarioForm.lblLogin.text")); // NOI18N
        lblLogin.setEnabled(false);
        lblLogin.setName("lblLogin"); // NOI18N

        edtLogin.setText(bundle.getString("FuncionarioForm.edtLogin.text")); // NOI18N
        edtLogin.setEnabled(false);
        edtLogin.setName("edtLogin"); // NOI18N

        lblSenha.setText(bundle.getString("FuncionarioForm.lblSenha.text")); // NOI18N
        lblSenha.setEnabled(false);
        lblSenha.setName("lblSenha"); // NOI18N

        lblPermissao.setText(bundle.getString("FuncionarioForm.lblPermissao.text")); // NOI18N
        lblPermissao.setEnabled(false);
        lblPermissao.setName("lblPermissao"); // NOI18N

        cbbPermissao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbPermissao.setEnabled(false);
        cbbPermissao.setName("cbbPermissao"); // NOI18N
        cbbPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPermissaoActionPerformed(evt);
            }
        });

        edtSenha.setText(bundle.getString("FuncionarioForm.edtSenha.text")); // NOI18N
        edtSenha.setEchoChar('X');
        edtSenha.setEnabled(false);
        edtSenha.setName("edtSenha"); // NOI18N

        chbAtivo.setSelected(true);
        chbAtivo.setText(bundle.getString("FuncionarioForm.chbAtivo.text")); // NOI18N
        chbAtivo.setEnabled(false);
        chbAtivo.setName("chbAtivo"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        btnBusscar.setBackground(new java.awt.Color(183, 28, 28));
        btnBusscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBusscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtro6.png"))); // NOI18N
        btnBusscar.setText(bundle.getString("FuncionarioForm.btnBusscar.text")); // NOI18N
        btnBusscar.setToolTipText(bundle.getString("FuncionarioForm.btnBusscar.toolTipText")); // NOI18N
        btnBusscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusscar.setName("btnBusscar"); // NOI18N
        btnBusscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusscarActionPerformed(evt);
            }
        });

        btnRemoverFiltro.setBackground(new java.awt.Color(224, 224, 224));
        btnRemoverFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/removeFiltro1.png"))); // NOI18N
        btnRemoverFiltro.setText(bundle.getString("FuncionarioForm.btnRemoverFiltro.text")); // NOI18N
        btnRemoverFiltro.setToolTipText(bundle.getString("FuncionarioForm.btnRemoverFiltro.toolTipText")); // NOI18N
        btnRemoverFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoverFiltro.setName("btnRemoverFiltro"); // NOI18N
        btnRemoverFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFiltroActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(14, 14, 14)
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(33, 33, 33)
                                .add(edtCpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel7))
                                .add(28, 28, 28)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(cbbBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jLabel11)
                                                .add(18, 18, 18)
                                                .add(edtSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(cbbCargo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(edtRg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(18, 18, 18)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(0, 0, Short.MAX_VALUE)
                                                .add(jLabel5))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jLabel3)
                                                .add(18, 18, 18)
                                                .add(edtDataAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(0, 0, Short.MAX_VALUE))))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cbbCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(65, 65, 65)
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jPanel1Layout.createSequentialGroup()
                                                            .add(lblPermissao)
                                                            .add(30, 30, 30)
                                                            .add(cbbPermissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                            .add(160, 160, 160)
                                                            .add(chbAtivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .add(jPanel1Layout.createSequentialGroup()
                                                            .add(38, 38, 38)
                                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                                .add(chbUsr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                .add(jPanel1Layout.createSequentialGroup()
                                                                    .add(lblLogin)
                                                                    .add(30, 30, 30)
                                                                    .add(edtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                            .add(92, 92, 92)
                                                            .add(lblSenha)
                                                            .add(36, 36, 36)
                                                            .add(edtSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .add(108, 108, 108)
                                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                            .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                            .add(jLabel8))
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .add(jLabel10)))))
                                        .add(89, 89, 89))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(34, 34, 34)
                                .add(edtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(559, 559, 559)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(edtEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(chbFun)
                                            .add(edtSalario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(26, 26, 26)
                                                .add(jLabel4))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(36, 36, 36)
                                                .add(jLabel6))
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel9)))
                                        .add(18, 18, 18)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(edtDataDem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(edtCarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(edtCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(btnBusscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(40, 40, 40)
                                        .add(btnRemoverFiltro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(300, 300, 300)
                        .add(btnNovo)
                        .add(61, 61, 61)
                        .add(btnSalvar)
                        .add(48, 48, 48)
                        .add(btnCancelar)
                        .add(109, 109, 109)
                        .add(btnSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(4, 4, 4)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1257, Short.MAX_VALUE)
                        .add(jSeparator2)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(6, 6, 6)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(edtCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(edtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(edtSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel3))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(12, 12, 12)
                                        .add(jLabel1))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel11))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(cbbCargo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel2)))
                            .add(edtDataAdm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cbbCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7)
                            .add(jLabel8)
                            .add(cbbBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10)
                            .add(edtEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(edtCpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(chbFun)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(12, 12, 12)
                                    .add(jLabel14)))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel15)
                                .add(edtRg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(edtDataDem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(edtCarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(edtSalario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 52, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(chbUsr)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(lblLogin))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(edtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(lblSenha))
                            .add(edtSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(5, 5, 5)
                                .add(lblPermissao))
                            .add(cbbPermissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(chbAtivo))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(btnBusscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(btnRemoverFiltro)))
                .add(56, 56, 56)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnNovo)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(btnCancelar)
                            .add(btnSalvar)
                            .add(btnSair))
                        .addContainerGap())))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(0, 177, Short.MAX_VALUE)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(34, 34, 34)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(64, 64, 64)
                    .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(65, 65, 65)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 288, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName(bundle.getString("FuncionarioForm.AccessibleContext.accessibleName")); // NOI18N

        setBounds(40, 50, 1265, 691);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Sair form.
     */
    public void sairForm(){
        ConfiguracaoMaster.fecharForm(this);
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        sairForm();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * Cancelar operacao.
     */
    public void cancelarOperacao() {
      
        Object[] options = {"Sim", "Não"};
        int resp = JOptionPane.showOptionDialog(null, "Deseja Cancelar a inclusão?", "Abortar Operação", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);

        if (resp == 0) {
            HabilitarCampos(false);
            DesabilitarButton(false);
            LimparCampos();
            chbAtivo.setText("Funcionário");
        } else {
            edtNome.requestFocus();
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarOperacao();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * Habilitar campos.
     *
     * @param b the b
     */
    public void HabilitarCampos(boolean b){
        
        edtNome.setEnabled(b);
        cbbCargo.setEnabled(b);
        edtDataAdm.setEnabled(b);
        edtDataDem.setEnabled(b);
        cbbCidade.setEnabled(b);
        cbbBairro.setEnabled(b);
        edtCep.setEnabled(b);
        edtEndereco.setEnabled(b);
        edtCpf.setEnabled(b);
        edtRg.setEnabled(b);
        edtSalario.setEnabled(b);
        edtCarga.setEnabled(b);
        chbUsr.setEnabled(b);
        edtSobrenome.setEnabled(b);
        
    }

    /**
     * Habilitar button.
     *
     * @param valor the valor
     */
    final void HabilitarButton(boolean valor) {

        btnNovo.setEnabled(!valor);
        btnSalvar.setEnabled(valor);
        btnBusscar.setEnabled(!valor);
        btnRemoverFiltro.setEnabled(!valor);
        btnCancelar.setEnabled(valor);        
        
      
    }
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        HabilitarCampos(true);
        BusscarRegistros();
        edtNome.requestFocus();
        HabilitarButton(true);

    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * Usr cred.
     *
     * @param b the b
     */
    public void usrCred(boolean b){
        edtLogin.setEnabled(b);
        edtSenha.setEnabled(b);
        cbbPermissao.setEnabled(b);
        chbAtivo.setEnabled(b);
        
        lblLogin.setEnabled(b);
        lblPermissao.setEnabled(b);
        lblSenha.setEnabled(b);
    }
    
    private void chbUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbUsrActionPerformed
        // TODO add your handling code here:
        
        if(chbUsr.isSelected()){
            chbUsr.setText("Usuário");
            usrCred(true);
            
        } else {
            chbUsr.setText("Funcionário");
            usrCred(false);
        }
    }//GEN-LAST:event_chbUsrActionPerformed

    private void cbbPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPermissaoActionPerformed

    private void edtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSalarioActionPerformed

    private void cbbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCidadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbCidadeActionPerformed

    private void cbbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCidadeItemStateChanged
        // TODO add your handling code here:
        Bairros.clear();
        IdBairro.clear();
        cbbBairro.removeAllItems();
        
        FuncionarioC.busscarBairro(IdCidade.get(cbbCidade.getSelectedIndex()), Bairros, IdBairro);
        for(String i: Bairros){
            cbbBairro.addItem(i);
        }
        
       
    }//GEN-LAST:event_cbbCidadeItemStateChanged

    private void btnBusscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusscarActionPerformed

    private void btnRemoverFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemoverFiltro;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbBairro;
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JComboBox<String> cbbCidade;
    private javax.swing.JComboBox<String> cbbPermissao;
    private javax.swing.JCheckBox chbAtivo;
    private javax.swing.JCheckBox chbFun;
    private javax.swing.JCheckBox chbUsr;
    private javax.swing.JTextField edtCarga;
    private javax.swing.JTextField edtCep;
    private javax.swing.JTextField edtCpf;
    private com.toedter.calendar.JDateChooser edtDataAdm;
    private com.toedter.calendar.JDateChooser edtDataDem;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtRg;
    private javax.swing.JFormattedTextField edtSalario;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JTextField edtSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPermissao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTable tblFuncionario;
    // End of variables declaration//GEN-END:variables

    private void DesabilitarButton(boolean valor) {
        btnNovo.setEnabled(!valor);
        btnSalvar.setEnabled(valor);
        btnBusscar.setEnabled(!valor);
        btnRemoverFiltro.setEnabled(!valor);
        btnCancelar.setEnabled(valor);
    }

    private void LimparCampos() {

        edtNome.setText(null);
        edtSobrenome.setText(null);
        cbbCargo.removeAllItems();
        cbbBairro.removeAllItems();
        cbbCidade.removeAllItems();
        
        
    }

    private void BusscarRegistros() {
        Cargo.clear();
        Cidades.clear();
        IdCidade.clear();
        
        FuncionarioC.busscarCargo(Cargo);
        Cargo.forEach((i) -> {
            cbbCargo.addItem(i);
        });
        
        FuncionarioC.busscarCidade(Cidades, IdCidade, Ordem);
        Cidades.forEach((i) -> {
            cbbCidade.addItem(i);
        });
        cbbCidade.setSelectedIndex(Ordem.indexOf(1));
    }
} 
